from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from ripozo_mongokit_tests.ripozo_mongokit_unittests import MongoKitManagerTests
